import { PERMISSIONS, Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  ADMIN: [
    PERMISSIONS.NEWS_CREATE,
    PERMISSIONS.NEWS_UPDATE,
    PERMISSIONS.NEWS_DELETE,
    PERMISSIONS.CATEGORY_MANAGE,
    PERMISSIONS.DOSEN_MANAGE,
    PERMISSIONS.STATISTIC_MANAGE,
    PERMISSIONS.VISION_MISSION_MANAGE,
    PERMISSIONS.PARTNERSHIP_MANAGE,
    PERMISSIONS.ALUMNI_MANAGE,
    PERMISSIONS.STUDY_MANAGE,
    PERMISSIONS.ACHIEVEMENT_MANAGE,
    PERMISSIONS.LECTURESHIP_MANAGE,
    PERMISSIONS.FACILITY_MANAGE,
  ],

  EDITOR: [PERMISSIONS.NEWS_CREATE, PERMISSIONS.NEWS_UPDATE],
};
